<a href="https://colab.research.google.com/github/namita0210/LearnDL-yt/blob/main/1_cnn_hands_on.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow.keras import layers,models

In [2]:
input_image=(1,28,28,1)

In [3]:
x=tf.random.normal(input_image)

In [4]:
y = layers.Conv2D(filters=1,kernel_size=3,input_shape=input_image[1:])(x)

In [5]:
print(y.shape)

(1, 26, 26, 1)


Using a Conv2D layer

In [6]:
# Same code with padding
input_image=(1,28,28,1)
x=tf.random.normal(input_image)
y=layers.Conv2D(filters=1,kernel_size=(3,3),padding="same",input_shape=input_image[1:])(x)
print(y.shape)

(1, 28, 28, 1)


Mathematical Operation behind the scenes in a convolutional neural network

In [9]:
#declare input image dimensions
input_image = (1,5,5,1)
# 1 --> no. of images ( batch size)
# 5,5 --> dimensions of the image
# 1--> grayscale image (only one channel)

In [14]:
#create input image as a matrix
x = tf.random.normal(input_image)
print(x.shape)

(1, 5, 5, 1)


In [19]:
#create conv layer
li = layers.Conv2D(
    filters=1,
    kernel_size=(3,3),
    input_shape = (input_image[1:])
)

In [22]:
#Mathematical proof of behind the scenes inside the Convolutional Layer
li.get_weights()
# These are the weights initialized for the kernel which is of 3x3 dimension

[array([[[[-0.497579  ]],
 
         [[-0.18928835]],
 
         [[ 0.15820026]]],
 
 
        [[[-0.566172  ]],
 
         [[-0.4245202 ]],
 
         [[-0.5146223 ]]],
 
 
        [[[-0.31765836]],
 
         [[-0.04379576]],
 
         [[ 0.4385277 ]]]], dtype=float32),
 array([0.], dtype=float32)]

In [21]:
#multiply the input with the layer to get output of convolution
y = li(x)
print(y.shape)

(1, 3, 3, 1)


Pooling - Average and Max

In [29]:
#Average Pooling
avg_pool = layers.AveragePooling2D(
    pool_size=(2,2),      # kernel
    strides=(2,2),        # move 2 pixels at a time
    padding="same"       # will not lose dimensions
    )

In [30]:
avg_pool(y)  # apply average pooling on the convolution layer output

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[-0.51941484],
         [-0.24437526]],

        [[-0.1331218 ],
         [-0.05721039]]]], dtype=float32)>

In [31]:
# Max Pooling
max_pool = layers.MaxPooling2D(
    pool_size=(2,2),
    strides=(2,2),
    padding="same"
)

In [32]:
#apply max pooling on the output of convolution layer
max_pool(y)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[ 0.1239616 ],
         [ 0.13285442]],

        [[ 0.06840169],
         [-0.05721039]]]], dtype=float32)>

Activation on Convolutional Operation

In [33]:
input_image=(1,5,5,1)

In [34]:
x=tf.random.normal(input_image)

In [35]:
l1=layers.Conv2D(
    filters=1,
    kernel_size=(3,3),
    padding="same",
    input_shape=input_image[1:],
    activation="relu"
)

In [36]:
y=l1(x)

In [37]:
y

<tf.Tensor: shape=(1, 5, 5, 1), dtype=float32, numpy=
array([[[[0.        ],
         [0.19951992],
         [1.4381114 ],
         [2.3894255 ],
         [0.45781207]],

        [[0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [1.8112683 ]],

        [[0.        ],
         [0.23227671],
         [0.29180124],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.58079875],
         [0.33310974],
         [0.59382284]],

        [[0.        ],
         [0.20345339],
         [0.81077987],
         [0.03048132],
         [0.        ]]]], dtype=float32)>

In [ ]:
k